version: '3.9'

services:
  
  mysql:
    image: mysql:8.0

    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=base
    volumes:
      - ./docker/database:/var/lib/mysql
    
    ports:
      - 33061:3306
    restart: always
